"""Build every understanding artifact from the raw corpus.

WHAT IS PRECOMPUTED, AND WHY
Precompute anything whose failure would be silent. Metric extraction,
sensitivity tagging and the retrieval index all fall in that category: a
mis-parsed figure discovered at query time is indistinguishable from a correct
one, so it is far better to produce it once, visibly, where it can be checked.

Compute live anything cheap and query-dependent — aggregation, ranking,
phrasing. Re-parsing a 300-page 10-K per question would be slow and, worse,
non-deterministic.

Four artifacts:
    facts.db          typed figures, queried by SQL
    index/bm25.json   narrative chunks, scored lexically
    summaries/*.json  per-document metadata and tag profile
    schema_notes.md   generated, human-readable description of the above
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import asdict
from pathlib import Path

from src.access.model import Tag
from src.ingest.chunker import chunk_corpus, load_config
from src.ingest.excel_loader import load_headcount_workbook, load_statement_workbook
from src.understanding.facts import Fact, build_facts_db, corpus_max_fy
from src.understanding.index import BM25Index

RAW = Path("data/raw")
OUT = Path("data/understanding")
CONFIG = Path("config/sources.yaml")


def collect_facts(raw_dir: Path = RAW) -> list[Fact]:
    """Every figure in the corpus, from both spreadsheet shapes."""
    facts: list[Fact] = []
    for workbook in sorted(raw_dir.glob("*.xlsx")):
        facts += load_statement_workbook(workbook)

    synthetic = raw_dir / "_synthetic" / "headcount_by_department.xlsx"
    if synthetic.exists():
        facts += load_headcount_workbook(synthetic)
    return facts


def write_summaries(chunks, facts, out_dir: Path) -> int:
    """One JSON per source document: what it is, and what it contains.

    This is the artifact that lets an agent decide *which* document to look in
    before searching it, and it is what `get_schema` returns to the model.
    """
    summaries_dir = out_dir / "summaries"
    summaries_dir.mkdir(parents=True, exist_ok=True)

    sources = {c.source for c in chunks} | {f.source for f in facts}
    for source in sorted(sources):
        doc_chunks = [c for c in chunks if c.source == source]
        doc_facts = [f for f in facts if f.source == source]
        summary = {
            "source": source,
            "chunks": len(doc_chunks),
            "facts": len(doc_facts),
            "fiscal_years": sorted({c.fiscal_year for c in doc_chunks}
                                   | {f.fiscal_year for f in doc_facts}),
            "periods": sorted({f.period for f in doc_facts}),
            "tags": dict(Counter([c.tag.value for c in doc_chunks]
                                 + [f.tag.value for f in doc_facts])),
            "sample_metrics": sorted({f.metric for f in doc_facts})[:25],
        }
        name = source.replace(".pdf", "").replace(".xlsx", "")
        (summaries_dir / f"{name}.json").write_text(
            json.dumps(summary, indent=2), encoding="utf-8")
    return len(sources)


def write_metric_tags(facts, out_dir: Path) -> int:
    """Map every metric name to EVERY tag it appears under.

    The planner must declare a plan's tags *before* any data is fetched — the
    guard cannot check what was not declared. Deriving the map from the ingested
    facts means it can never disagree with what is actually stored.

    A metric legitimately spans tags: `net_sales` is reported both in the
    consolidated statement (`financials.statements`) and in the segment
    breakdown (`financials.segment`). An earlier version collapsed that to the
    single most-restrictive tag, which was safe but described the data wrongly —
    it claimed consolidated net sales was segment data. Recording the full set
    and declaring all of it keeps the plan honest and still fails closed: the
    guard refuses if *any* declared tag is denied.
    """
    mapping: dict[str, set[str]] = {}
    for fact in facts:
        mapping.setdefault(fact.metric, set()).add(fact.tag.value)

    (out_dir / "metric_tags.json").write_text(
        json.dumps({m: sorted(tags) for m, tags in sorted(mapping.items())},
                   indent=2),
        encoding="utf-8")
    return len(mapping)


def write_schema_notes(chunks, facts, out_dir: Path) -> None:
    """Human-readable description of what was extracted.

    Generated rather than hand-written so it cannot drift from the data.
    """
    tag_counts = Counter([c.tag.value for c in chunks]
                         + [f.tag.value for f in facts])
    metrics = sorted({f.metric for f in facts})
    periods = sorted({f.period for f in facts})

    lines = [
        "# Schema Notes",
        "",
        "Generated by `scripts/build_understanding.py`. Do not edit by hand.",
        "",
        "## Facts (`facts.db`)",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| metric | normalised name, e.g. `net_sales`, `iphone_net_sales` |",
        "| value | the reported figure |",
        "| unit | `USD_M` for statement figures, `people` for headcount |",
        "| period | `FY2025` or `Q3FY2026` |",
        "| fiscal_year | the year the figure describes, not the filing year |",
        "| source | filing the figure came from |",
        "| locator | `Sheet!R12C3`, so any figure can be checked |",
        "| tag | sensitivity label the access gate enforces |",
        "",
        f"- **{len(facts):,} facts**, {len(metrics):,} distinct metrics",
        f"- Periods: {', '.join(periods)}",
        "",
        "## Chunks (`index/bm25.json`)",
        "",
        f"- **{len(chunks):,} chunks** from the PDF filings",
        f"- Average length: {sum(len(c.text) for c in chunks) // max(len(chunks), 1)}"
        " characters",
        "- Each carries source, page, fiscal year and tag",
        "",
        "## Sensitivity tags across both stores",
        "",
        "| Tag | Records |",
        "|---|---|",
    ]
    for tag, count in tag_counts.most_common():
        lines.append(f"| `{tag}` | {count:,} |")

    lines += [
        "",
        "## Sample metric names",
        "",
        "```",
        *metrics[:40],
        "```",
    ]
    (out_dir / "schema_notes.md").write_text("\n".join(lines) + "\n",
                                             encoding="utf-8")


def build_all(raw_dir: Path = RAW, out_dir: Path = OUT,
              config_path: Path = CONFIG) -> dict:
    """Produce every artifact. Returns a report for the caller to print."""
    cfg = load_config(config_path)

    facts = collect_facts(raw_dir)
    chunks = chunk_corpus(raw_dir, cfg)

    out_dir.mkdir(parents=True, exist_ok=True)
    fact_count = build_facts_db(facts, out_dir / "facts.db")

    index = BM25Index.build(chunks)
    index.save(out_dir / "index" / "bm25.json")

    documents = write_summaries(chunks, facts, out_dir)
    metrics = write_metric_tags(facts, out_dir)
    write_schema_notes(chunks, facts, out_dir)

    return {
        "facts": fact_count,
        "chunks": len(chunks),
        "documents": documents,
        "metrics": metrics,
        "corpus_max_fy": corpus_max_fy(out_dir / "facts.db"),
        "tags": dict(Counter([c.tag.value for c in chunks]
                             + [f.tag.value for f in facts])),
    }
